apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer   # exposes external IP
  selector:
    app: fastapi-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
